spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
     
application:
  security:
    jwt:
      secret-key: 3777217A25432A462D4A614E635266556A586E3272357538782F413F4428472B
      expiration: 604800000 # 86400000 # a day
    